/**
 * ax-templates CLI - Init Command
 * Initialize a new ax-templates project
 */

import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import boxen from 'boxen';
import { existsSync, mkdirSync, writeFileSync, copyFileSync, readdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { stringify as yamlStringify } from 'yaml';
import { fileURLToPath } from 'node:url';
import {
  CONFIG_FILENAME,
  DEFAULT_STAGES,
  createInitialProgress,
  type AxConfig,
} from '@ax-templates/core';
import { runInitWizard, answersToConfig, getQuickInitConfig } from '../prompts/init-wizard.js';

// Get the directory of this file
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export const initCommand = new Command('init')
  .description('Initialize a new ax-templates project')
  .argument('[project-name]', 'Project name')
  .option('-y, --yes', 'Skip prompts and use defaults')
  .option('--template <name>', 'Template to use', 'default')
  .action(async (projectName?: string, options?: { yes?: boolean; template?: string }) => {
    await executeInit(projectName, options);
  });

async function executeInit(
  projectName?: string,
  options: { yes?: boolean; template?: string } = {}
) {
  console.log();
  console.log(chalk.cyan.bold('🚀 ax-templates 프로젝트 초기화'));
  console.log();

  // Determine target directory
  const targetDir = projectName ? resolve(process.cwd(), projectName) : process.cwd();

  // Check if directory exists with config
  if (existsSync(join(targetDir, CONFIG_FILENAME))) {
    console.log(chalk.yellow('⚠️  이 디렉토리에 이미 ax-templates 프로젝트가 있습니다.'));
    console.log(chalk.gray(`   ${join(targetDir, CONFIG_FILENAME)}`));
    return;
  }

  // Get configuration
  let config: Partial<AxConfig>;

  if (options.yes) {
    // Quick init with defaults
    const name = projectName || 'my-project';
    config = getQuickInitConfig(name);
    console.log(chalk.gray('기본 설정으로 초기화합니다...'));
  } else {
    // Run interactive wizard
    const answers = await runInitWizard(projectName);
    config = answersToConfig(answers);
  }

  // Create project structure
  const spinner = ora('프로젝트 구조 생성 중...').start();

  try {
    // Create target directory if needed
    if (!existsSync(targetDir)) {
      mkdirSync(targetDir, { recursive: true });
    }

    // Create directories
    const dirs = [
      config.paths!.stages_output!,
      config.paths!.state!,
      config.paths!.checkpoints!,
      join(config.paths!.state!, 'context'),
      join(config.paths!.state!, 'handoffs'),
    ];

    for (const dir of dirs) {
      const fullPath = join(targetDir, dir);
      if (!existsSync(fullPath)) {
        mkdirSync(fullPath, { recursive: true });
      }
    }

    spinner.succeed('디렉토리 구조 생성됨');

    // Create config file
    spinner.start('.ax-config.yaml 생성 중...');
    const configPath = join(targetDir, CONFIG_FILENAME);
    const configContent = yamlStringify(config, { indent: 2 });
    writeFileSync(configPath, `# ax-templates Configuration\n# Generated by ax init\n\n${configContent}`);
    spinner.succeed('.ax-config.yaml 생성됨');

    // Create stages from template
    spinner.start('스테이지 템플릿 복사 중...');
    await copyStageTemplates(targetDir, config.paths!.stages_output!, options.template || 'default');
    spinner.succeed('스테이지 템플릿 복사됨');

    // Initialize progress.json
    spinner.start('progress.json 초기화 중...');
    const progressPath = join(targetDir, config.paths!.state!, 'progress.json');
    const initialProgress = createInitialProgress();
    writeFileSync(progressPath, JSON.stringify(initialProgress, null, 2));
    spinner.succeed('progress.json 초기화됨');

    // Create CLAUDE.md
    spinner.start('CLAUDE.md 생성 중...');
    await createClaudeMd(targetDir, config);
    spinner.succeed('CLAUDE.md 생성됨');

    // Copy config directory
    spinner.start('설정 파일 복사 중...');
    await copyConfigFiles(targetDir);
    spinner.succeed('설정 파일 복사됨');

    // Copy scripts
    spinner.start('스크립트 복사 중...');
    await copyScripts(targetDir);
    spinner.succeed('스크립트 복사됨');

    console.log();

    // Success message
    const successMessage = boxen(
      `${chalk.green.bold('✓ 프로젝트가 성공적으로 초기화되었습니다!')}\n\n` +
      `${chalk.gray('다음 단계:')}\n` +
      `${chalk.white('1.')} ${chalk.cyan('stages/01-brainstorm/inputs/project_brief.md')} 편집\n` +
      `${chalk.white('2.')} ${chalk.cyan('ax brainstorm')} 실행\n\n` +
      `${chalk.gray('도움말:')} ${chalk.cyan('ax --help')}`,
      {
        padding: 1,
        margin: 1,
        borderStyle: 'round',
        borderColor: 'green',
      }
    );

    console.log(successMessage);

  } catch (error) {
    spinner.fail('초기화 실패');
    console.error(chalk.red('오류:'), error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

async function copyStageTemplates(
  targetDir: string,
  stagesOutput: string,
  template: string
): Promise<void> {
  // For each default stage, create the directory structure
  for (const stage of DEFAULT_STAGES) {
    const stageDir = join(targetDir, stagesOutput, stage.id);

    // Create directories
    mkdirSync(join(stageDir, 'inputs'), { recursive: true });
    mkdirSync(join(stageDir, 'outputs'), { recursive: true });
    mkdirSync(join(stageDir, 'prompts'), { recursive: true });
    mkdirSync(join(stageDir, 'templates'), { recursive: true });

    // Create stage config.yaml
    const stageConfig = {
      stage: {
        id: stage.id,
        name: stage.name,
        description: stage.description,
      },
      execution: {
        models: stage.models,
        mode: stage.mode,
        timeout: stage.timeout,
        checkpoint_required: stage.checkpoint_required ?? false,
      },
      io: {
        inputs: stage.inputs,
        outputs: stage.outputs,
      },
    };

    writeFileSync(
      join(stageDir, 'config.yaml'),
      yamlStringify(stageConfig, { indent: 2 })
    );

    // Create stage CLAUDE.md
    const claudeMd = `# ${stage.name}

> 스테이지 ID: ${stage.id}
> 모델: ${stage.models.join(', ')}
> 모드: ${stage.mode}

## 개요

${stage.description}

## 입력

${stage.inputs.map(i => `- \`${i}\``).join('\n')}

## 출력

${stage.outputs.map(o => `- \`${o}\``).join('\n')}

## 지침

(이 스테이지의 구체적인 지침을 작성하세요)
`;

    writeFileSync(join(stageDir, 'CLAUDE.md'), claudeMd);

    // Create README.md
    const readme = `# ${stage.name}

${stage.description}

## 실행 방법

\`\`\`bash
ax ${stage.id.split('-')[1]} # or ax run-stage ${stage.id}
\`\`\`

## 입력 파일

${stage.inputs.map(i => `- \`inputs/${i}\``).join('\n')}

## 출력 파일

${stage.outputs.map(o => `- \`outputs/${o}\``).join('\n')}
`;

    writeFileSync(join(stageDir, 'README.md'), readme);

    // Create input placeholder files for first stage
    if (stage.id === '01-brainstorm') {
      const projectBrief = `# Project Brief

## 프로젝트 이름

(프로젝트 이름을 입력하세요)

## 프로젝트 설명

(프로젝트 설명을 입력하세요)

## 목표

- (목표 1)
- (목표 2)
- (목표 3)

## 대상 사용자

(대상 사용자를 설명하세요)

## 기술 제약 조건

(있다면 기술 제약 조건을 나열하세요)
`;
      writeFileSync(join(stageDir, 'inputs', 'project_brief.md'), projectBrief);

      const userRequirements = `# User Requirements

## 기능 요구사항

### 필수 기능
- (필수 기능 1)
- (필수 기능 2)

### 선택 기능
- (선택 기능 1)

## 비기능 요구사항

- 성능:
- 보안:
- 확장성:

## 우선순위

1. (최우선 항목)
2. (두 번째 항목)
3. (세 번째 항목)
`;
      writeFileSync(join(stageDir, 'inputs', 'user_requirements.md'), userRequirements);
    }
  }
}

async function createClaudeMd(targetDir: string, config: Partial<AxConfig>): Promise<void> {
  const claudeMd = `# ax-templates - Multi-AI Workflow Pipeline

10단계 소프트웨어 개발 워크플로우 템플릿 시스템

## 프로젝트 설정

> 설정 파일: \`.ax-config.yaml\`

### 경로 설정
- 소스코드: \`${config.paths?.project_root}\`
- 스테이지 산출물: \`${config.paths?.stages_output}\`
- 상태 파일: \`${config.paths?.state}\`

### AI CLI
- Gemini: ${config.ai?.gemini ? '활성화' : '비활성화'}
- Codex: ${config.ai?.codex ? '활성화' : '비활성화'}

### 컨텍스트 임계값
- 경고: ${config.context?.warning}%
- 액션: ${config.context?.action}%
- 크리티컬: ${config.context?.critical}%

## 파이프라인 개요

| 단계 | 이름 | AI 모델 | 실행 모드 |
|------|------|---------|-----------|
| 01 | Brainstorming | Gemini + ClaudeCode | YOLO (Container) |
| 02 | Research | Claude | Plan Mode |
| 03 | Planning | Gemini | Plan Mode |
| 04 | UI/UX Planning | Gemini | Plan Mode |
| 05 | Task Management | ClaudeCode | Plan Mode |
| 06 | Implementation | ClaudeCode | Plan + Sandbox |
| 07 | Refactoring | Codex | Deep Dive |
| 08 | QA | ClaudeCode | Plan + Sandbox |
| 09 | Testing & E2E | Codex | Sandbox + Playwright |
| 10 | CI/CD & Deployment | ClaudeCode | Headless |

## 슬래시 커맨드

| 커맨드 | 설명 |
|--------|------|
| \`/init-project\` | 새 프로젝트 초기화 |
| \`/run-stage [id]\` | 특정 스테이지 실행 |
| \`/handoff\` | 현재 스테이지 HANDOFF.md 생성 |
| \`/checkpoint\` | 체크포인트 생성 |
| \`/status\` | 파이프라인 전체 상태 확인 |
| \`/stages\` | 스테이지 목록 및 상세 |
| \`/context\` | 컨텍스트(토큰) 상태 관리 |
| \`/next\` | 다음 스테이지로 전환 |
| \`/restore\` | 체크포인트에서 복구 |

## 금지 사항

- HANDOFF.md 없이 스테이지 전환
- 체크포인트 없이 파괴적 작업 (구현/리팩토링)
- 단일 세션에 복수 스테이지 혼합
- 이전 스테이지 outputs 수정
`;

  writeFileSync(join(targetDir, 'CLAUDE.md'), claudeMd);
}

async function copyConfigFiles(targetDir: string): Promise<void> {
  const configDir = join(targetDir, 'config');
  if (!existsSync(configDir)) {
    mkdirSync(configDir, { recursive: true });
  }

  // Create pipeline.yaml
  const pipelineConfig = {
    pipeline: {
      name: 'Multi-AI Development Workflow',
      version: '1.0.0',
      description: '10-stage software development workflow with multi-AI orchestration',
    },
    stages: DEFAULT_STAGES,
    state_management: {
      progress_file: 'state/progress.json',
      checkpoints_dir: 'state/checkpoints',
      context_dir: 'state/context',
      handoffs_dir: 'state/handoffs',
    },
  };

  writeFileSync(
    join(configDir, 'pipeline.yaml'),
    yamlStringify(pipelineConfig, { indent: 2 })
  );

  // Create models.yaml
  const modelsConfig = {
    models: {
      claudecode: {
        provider: 'anthropic',
        model_id: 'claude-sonnet-4-20250514',
        description: 'Primary coding agent with tool use',
      },
      claude: {
        provider: 'anthropic',
        model_id: 'claude-sonnet-4-20250514',
        description: 'Research and analysis specialist',
      },
      gemini: {
        provider: 'google',
        cli_command: 'gemini',
        description: 'Brainstorming and creative planning',
      },
      codex: {
        provider: 'openai',
        cli_command: 'codex',
        description: 'Code optimization and refactoring',
      },
    },
  };

  writeFileSync(
    join(configDir, 'models.yaml'),
    yamlStringify(modelsConfig, { indent: 2 })
  );
}

async function copyScripts(targetDir: string): Promise<void> {
  const scriptsDir = join(targetDir, 'scripts');
  if (!existsSync(scriptsDir)) {
    mkdirSync(scriptsDir, { recursive: true });
  }

  // Create gemini-wrapper.sh
  const geminiWrapper = `#!/bin/bash
# gemini-wrapper.sh - tmux 기반 Gemini CLI 래퍼

SESSION_NAME="\${AX_GEMINI_SESSION:-ax-gemini}"
CHANNEL="ax-gemini-done-\$\$"
OUTPUT_FILE="/tmp/ax-gemini-output-\$\$"
PROMPT="\$1"
TIMEOUT="\${2:-300}"

if [ -z "\$PROMPT" ]; then
    echo "사용법: \$0 \\"<prompt>\\" [timeout_seconds]"
    exit 1
fi

if ! command -v tmux &> /dev/null; then
    echo "오류: tmux가 설치되어 있지 않습니다."
    exit 1
fi

if ! command -v gemini &> /dev/null; then
    echo "경고: gemini CLI가 설치되어 있지 않습니다."
    exit 0
fi

cleanup() { rm -f "\$OUTPUT_FILE"; }
trap cleanup EXIT

if ! tmux has-session -t "\$SESSION_NAME" 2>/dev/null; then
    tmux new-session -d -s "\$SESSION_NAME"
    sleep 1
fi

ESCAPED_PROMPT=\$(printf '%s' "\$PROMPT" | sed 's/"/\\\\"/g')
tmux send-keys -t "\$SESSION_NAME" "gemini \\"\$ESCAPED_PROMPT\\" 2>&1 | tee \$OUTPUT_FILE; tmux wait-for -S \$CHANNEL" Enter

(sleep "\$TIMEOUT" && tmux wait-for -S "\$CHANNEL" 2>/dev/null) &
TIMER_PID=\$!
tmux wait-for "\$CHANNEL"
kill \$TIMER_PID 2>/dev/null || true

if [[ -f "\$OUTPUT_FILE" ]]; then
    cat "\$OUTPUT_FILE"
else
    echo "오류: 출력을 캡처하지 못했습니다."
    exit 1
fi
`;

  writeFileSync(join(scriptsDir, 'gemini-wrapper.sh'), geminiWrapper, { mode: 0o755 });

  // Create codex-wrapper.sh
  const codexWrapper = `#!/bin/bash
# codex-wrapper.sh - tmux 기반 Codex CLI 래퍼

SESSION_NAME="\${AX_CODEX_SESSION:-ax-codex}"
CHANNEL="ax-codex-done-\$\$"
OUTPUT_FILE="/tmp/ax-codex-output-\$\$"
PROMPT="\$1"
TIMEOUT="\${2:-300}"

if [ -z "\$PROMPT" ]; then
    echo "사용법: \$0 \\"<prompt>\\" [timeout_seconds]"
    exit 1
fi

if ! command -v tmux &> /dev/null; then
    echo "오류: tmux가 설치되어 있지 않습니다."
    exit 1
fi

if ! command -v codex &> /dev/null; then
    echo "경고: codex CLI가 설치되어 있지 않습니다."
    exit 0
fi

cleanup() { rm -f "\$OUTPUT_FILE"; }
trap cleanup EXIT

if ! tmux has-session -t "\$SESSION_NAME" 2>/dev/null; then
    tmux new-session -d -s "\$SESSION_NAME"
    sleep 1
fi

ESCAPED_PROMPT=\$(printf '%s' "\$PROMPT" | sed 's/"/\\\\"/g')
tmux send-keys -t "\$SESSION_NAME" "codex \\"\$ESCAPED_PROMPT\\" 2>&1 | tee \$OUTPUT_FILE; tmux wait-for -S \$CHANNEL" Enter

(sleep "\$TIMEOUT" && tmux wait-for -S "\$CHANNEL" 2>/dev/null) &
TIMER_PID=\$!
tmux wait-for "\$CHANNEL"
kill \$TIMER_PID 2>/dev/null || true

if [[ -f "\$OUTPUT_FILE" ]]; then
    cat "\$OUTPUT_FILE"
else
    echo "오류: 출력을 캡처하지 못했습니다."
    exit 1
fi
`;

  writeFileSync(join(scriptsDir, 'codex-wrapper.sh'), codexWrapper, { mode: 0o755 });
}
